### ISSUE TITLE
Invalid layer index in Cell.begin_shapes_rec_touching

### ISSUE THREAD

**Issue by lichiyang76** [s910324/CenterRulerPlugin#1]
Hi, Sir

Appreciate your developing the promising feature on Klayout, however one of difficulty I encountered.
Shall I have some advices or suggestions how can I resolve it?
Invalid layer index in Cell.begin_shapes_rec_touching in Plugin.mouse_moved_event
  C:/~/KLayout/salt/CenterRulerPlugin/pymacros\CenterRulerPlugin.lym:383
  C:/~/KLayout/salt/CenterRulerPlugin/pymacros\CenterRulerPlugin.lym:288

Thanks,

**Comment by s910324** [comment]
Hi @lichiyang76 

Thanks for the feedback, can you help me check under what kind of condition this error can be triggered?

For example when cursor move close to cetrain type of object or after cetrain type of operation?

Currently I have some difficulty reproducing this error.

**Comment by lichiyang76** [comment]
Hi @s910324 

Nice to hearing from you promptly, the message shown after moving the cursor into layout view window.
1) Select the object.
2) Click the bottom "Center Ruler".
3) Switch ruler type, etc...
4) Moving the cursor into window >> error message shown.

Hope it might help to feature out the reason, thanks!
![image](https://github.com/s910324/CenterRulerPlugin/assets/144640589/d40bf8b5-9530-40e8-afe0-ad3fa3f00dd8)

**Comment by s910324** [comment]
Hi @lichiyang76 
I've made some change to the Layer Indexing, now this should work properly 
the patch is on version 0.01, update to the newest version should solve the problem.

Thanks for the testing!

**Comment by lichiyang76** [comment]
Hi @s910324 
The updated revision is great, and works perfectly!  Appreciated!

**Comment by s910324** [comment]
😁
